### ISSUE TITLE
New failures on CRAN

### ISSUE THREAD

**Issue by adibender** [adibender/coalitions#129]
https://cran.r-project.org/web/checks/check_results_coalitions.html

I think most of them are related to `tbl_df` vs. `as_tibble`, which has been fixed in the latest PR. But I also got "ripleyed": 

> > Dear maintainer,
> >
> > Please see the problems shown on
> > <https://cran.r-project.org/web/checks/check_results_coalitions.html>.
> >
> > Please correct before 2020-08-29 to safely retain your package on CRAN.
> >
> > The CRAN Team
> 
> This is not complying with the CRAN policy
> 
> 'Packages which use Internet resources should fail gracefully with an
> informative message if the resource is not available or has changed (and
> not give a check warning nor error).'
> 
> and taking 90m to fail its tests is anti-social.

@bauer-alex do you have time to look into this? Not sure where the 90m come from?

**Comment by bauer-alex** [comment]
Sorry, was on vacation. :-/

Is this still pending, since the above stated deadline was August 29?

**Comment by adibender** [comment]
no sorry, forgot to close. all good now
