### ISSUE TITLE
Scraping data still not working for some institutes

### ISSUE THREAD

**Issue by bauer-alex** [adibender/coalitions#14]
Errors are arising for INSA and ForschGrWahlen:
`coalitions::scrape_wahlrecht("http://www.wahlrecht.de/umfragen/insa.htm")`
`coalitions::scrape_wahlrecht("http://www.wahlrecht.de/umfragen/politbarometer.htm")`

**Comment by adibender** [comment]
yeah, the INSA Table @wahlrecht is a catastrophe!! 

For FGW it should work with http://www.wahlrecht.de/umfragen/politbarometer/stimmung.htm
Or do we want the projection?

**Comment by bauer-alex** [comment]
Unfortunately we want the projection, as this is what we get from the other institutes...
