### ISSUE TITLE
get_surveys() possibly needs refinement

### ISSUE THREAD

**Issue by bauer-alex** [adibender/coalitions#51]
Applying `coalitions::get_surveys()` leads to warnings I've never had before:
e.g. `In extract_num(cdu) : NAs durch Umwandlung erzeugt`

Possibly a problem caused by the first line of the Emnid/Forsa/... tables on wahlrecht.de, which currently are no surveys, but show the btw17 result?

**Comment by adibender** [comment]
Exactly. Extra warnings due to wahlrecht.de includes btw17 results. Scrappring appears to work correctly nevertheless.
