### ISSUE TITLE
Bug in pool_surveys()

### ISSUE THREAD

**Issue by bauer-alex** [adibender/coalitions#52]
There is a new LTW survey where CDU and SPD have exactly the same result. Because of this, the `pool_survey()` function brings up an error.

Cause of the error: The `max_party` object has to be only one party (which is used for the effective sample size in the function), but with the two parties having the same share `max_party` is a vector of the two parties.

Solution: Just add `max_party <- max_party[1]` or something like that

**Comment by adibender** [comment]
done
