### ISSUE TITLE
Hex sticker? 

### ISSUE THREAD

**Issue by adibender** [adibender/coalitions#73]
@bauer-alex Do you want to create a hex-sticker for the package? 
Example: https://github.com/tidyverse/dplyr/blob/master/man/figures/logo.png

**Comment by bauer-alex** [comment]
@adibender How's the following?
![hexsticker_coalitions](https://user-images.githubusercontent.com/20172676/36964777-083e7eec-2058-11e8-8d1f-c17721843715.png)

**Comment by adibender** [comment]
cool, but maybe a little borrng? 
Maybe some structured surface instead of plain grey background? Or some background graphic? 

But I think it'll do for now. We can adjust later on. 

BTW: Apparently there's a R-package for this: https://github.com/GuangchuangYu/hexSticker

**Comment by bauer-alex** [comment]
Guess what I've used for creating the sticker. ;-)

I know it's a little boring, but I'd also leave it like that for now and maybe adjust it later on.

**Comment by adibender** [comment]
ah, nice :-) :+1: 
Can you PR  and embed in the README /homepage?

**Comment by bauer-alex** [comment]
done with newest PR
