### ISSUE TITLE
scrape_wahlrecht not working

### ISSUE THREAD

**Issue by bauer-alex** [adibender/coalitions#9]
scrape_wahlrecht isn't working anymore...

![unbenannt](https://cloud.githubusercontent.com/assets/20172676/23706097/0e5ca28a-040d-11e7-8fde-865205de162d.png)

**Comment by andinatro** [comment]
EDIT: Never mind, there seem to be some larger issues, e.g. the `%` character is not removed from the "GRÜNE" party count.

edit2: The umlaut might be the problem?

**Comment by andinatro** [comment]
Seems to be working when using UTF-8 encoding for the whole package.

**Comment by andinatro** [comment]
Actually, why not replace all umlauts with their "ae", ... counterparts instead of just turning "GRÜNE" and "Grünen" into "GRUENE" (`sanitize_colnames`)?

Replacing "Grünen" should not work anyways, because the whole character vector is capitalized beforehand.

**Comment by adibender** [comment]
Encoding issues probably key here. On Linux everything works fine (devel branch). 
Need to find a way to escape special characters. See also Warnings in `devtools::check()`.

**Comment by adibender** [comment]
```
checking R files for non-ASCII characters ... WARNING
Found the following file with non-ASCII characters:
  scrappers.R
Portable packages must use only ASCII characters in their R code,
except perhaps in comments.
Use \uxxxx escapes for other characters.

```

Tried to fix this, but didn't quiet work out yet.

**Comment by adibender** [comment]
Hat jetzt geklappt denke ich: https://en.wikipedia.org/wiki/List_of_Unicode_characters. 
Mache gleich update der Master branch. Ihr könnt es dann ja nochmal ausprobieren.
